packages:
  - packages/*
  - website
  - example

allowedDeprecatedVersions:
  '@types/minimatch': ^6.0.0
  glob: ^7.2.3
  inflight: ^1.0.6

catalog:
  '@element-plus/icons-vue': ^2.3.2
  '@rollup/plugin-terser': ^0.4.4
  '@tailwindcss/vite': ^4.1.17
  '@types/lodash': ^4.17.21
  '@types/node': ^24.10.1
  '@vitejs/plugin-vue': ^6.0.2
  '@vitejs/plugin-vue-jsx': ^5.1.2
  csstype: ^3.2.3
  element-plus: ^2.11.9
  glob: ^11.1.0
  lodash: ^4.17.21
  postcss: ^8.5.6
  postcss-nested: ^7.0.2
  rimraf: ^6.1.2
  rollup: ^4.53.3
  rollup-plugin-copy: ^3.5.0
  slate-vue3: ^0.9.3
  tailwind-scrollbar: ^4.0.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  unplugin-element-plus: ^0.11.1
  vite: ^7.2.4
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vue: ^3.5.25
  vue-tsc: ^3.1.5

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - vue-demi

overrides:
  lodash: $lodash

shellEmulator: true

strictPeerDependencies: true
