packages:
  - packages/*
  - website
  - example

allowedDeprecatedVersions:
  '@types/minimatch': ^6.0.0
  glob: ^7.2.3
  inflight: ^1.0.6

catalog:
  '@element-plus/icons-vue': ^2.3.2
  '@highlightjs/vue-plugin': ^2.1.0
  '@popperjs/core': ^2.11.8
  '@rollup/plugin-terser': ^0.4.4
  '@tailwindcss/vite': ^4.2.1
  '@types/file-saver': ^2.0.7
  '@types/lodash': ^4.17.24
  '@types/node': ^24.10.13
  '@types/howler': ^2.2.12
  '@vitejs/plugin-vue': ^6.0.4
  '@vitejs/plugin-vue-jsx': ^5.1.4
  cmu-pronouncing-dictionary: ^3.0.0
  csstype: ^3.2.3
  dayjs: ^1.11.19
  element-plus: ^2.13.2
  file-saver: ^2.0.5
  glob: ^13.0.6
  highlight.js: ^11.11.1
  howler: ^2.2.4
  is-what: ^5.5.0
  localforage: ^1.10.0
  lodash: ^4.17.23
  mathjs: ^15.1.1
  pinyin-pro: ^3.28.0
  pinyinize: ^3.3.1
  postcss: ^8.5.6
  postcss-nested: ^7.0.2
  rimraf: ^6.1.3
  rollup: ^4.59.0
  rollup-plugin-copy: ^3.5.0
  slate-vue3: ^0.13.1
  tailwind-scrollbar: ^4.0.2
  tailwindcss: ^4.2.1
  typescript: ^5.9.3
  typescript-event-emitter: ^2.1.0
  unplugin-element-plus: ^0.11.2
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vue: ^3.5.28
  vue-tsc: ^3.2.5
  xml-formatter: ^3.6.7

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - vue-demi

overrides:
  lodash: $lodash

shellEmulator: true

strictPeerDependencies: true
